# Generated by Django 4.2.3 on 2023-07-12 05:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('author', models.CharField(default='', max_length=50)),
                ('category', models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('science', 'Science')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('isbn', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.book')),
            ],
        ),
        migrations.AlterField(
            model_name='extrauserinfo',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now=True)),
                ('return_date', models.DateField(default=datetime.datetime(2023, 7, 20, 10, 56, 48, 891285))),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.bookinstance')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
