# Generated by Django 4.1.2 on 2023-07-13 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_book_bookinstance_alter_extrauserinfo_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='is_borrowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 21, 9, 58, 25, 565911)),
        ),
    ]
