# Generated by Django 4.1.2 on 2023-07-13 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0003_bookinstance_is_borrowed_alter_issuebook_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 21, 10, 12, 32, 246980)),
        ),
    ]
