# Generated by Django 4.1.2 on 2023-07-13 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0004_alter_issuebook_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='is_borrowed',
            field=models.CharField(default='false', max_length=10),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 21, 10, 14, 7, 742882)),
        ),
    ]
