# Generated by Django 4.1.2 on 2023-07-13 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0005_alter_bookinstance_is_borrowed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='is_borrowed',
        ),
        migrations.AddField(
            model_name='issuebook',
            name='is_borrowed',
            field=models.CharField(default='false', max_length=10),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 21, 10, 39, 49, 398074)),
        ),
    ]
