# Generated by Django 4.2.3 on 2023-07-13 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0007_alter_issuebook_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='is_borrowed',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='is_borrowed',
            field=models.CharField(default='false', max_length=10),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 21, 14, 21, 54, 70145)),
        ),
    ]
